DROP TABLE IF EXISTS `user`;

CREATE TABLE `user`
(
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID'
        PRIMARY KEY,
    userAccount VARCHAR(256) NULL COMMENT '账号',
    userName VARCHAR(256) NULL COMMENT '用户名称',
    avatarUrl VARCHAR(1024) NULL COMMENT '用户头像',
    gender TINYINT NULL COMMENT '性别',
    userPassword VARCHAR(512) NOT NULL COMMENT '用户密码',
    phone VARCHAR(128) NULL COMMENT '手机',
    email VARCHAR(512) NULL COMMENT '邮箱',
    userStatus INT NOT NULL DEFAULT 1 COMMENT '用户状态',
    createTime DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updateTime DATETIME NOT NULL DEFAULT  CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    isDelete TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除'
);